### ISSUE TITLE
v2.1版本无法登录

### ISSUE THREAD

**Issue by yanghuan** [txperl/PixivBiu#18]
我软路由上已经有代理了，浏览器也可以直接访问pixiv官网，但是使用PixivBiu一直无法使用，请问是什么原因？

```
[PixivBiu] 检测更新失败，可能是目标服务器过长时间未响应
[PixivBiu] 检测网络状态...
[PixivBiu] 无法访问 Pixiv，启用 byPassSni API
[PixivBiu] 由于 Pixiv 禁止了账号密码登陆方式，暂时只能使用 Token 进行登录
是否开始手动获取 Token 后继续使用? (y / n): y
[Login Helper] 即将开始进行网络检测，此过程可以减少因网络问题导致的无法正常使用 PixivBiu 的概率
[Login Helper] 开始进行网络检测...
检测到内容为 127.0.0.1:1082 的代理监听地址，是否需要更改? (y / n): y
请输入代理监听地址(可留空):
[Network Checker] https://public-api.secure.pixiv.net ❌
[Network Checker] https://1.0.0.1/dns-query ✔️
[Network Checker] https://1.1.1.1/dns-query ✔️
[Network Checker] https://[2606:4700:4700::1001]/dns-query ❌
[Network Checker] https://[2606:4700:4700::1111]/dns-query ❌
[Network Checker] https://cloudflare-dns.com/dns-query ✔️
[Login] 请按以下步骤进行操作:
注意: 程序每次启动时要求获取的 Code 都不同，不可复用之前获取到的，且 Code 不带有引号
1. 访问「https://app-api.pixiv.net/web/v1/login?code_challenge=0FOMIlDnmWof4OBd7gMeaztcOturSsskAdZooCA9Bh8&code_challenge_method=S256&client=pixiv-android」
   (若您别无他法，还是不能访问以上网址，那可参考此方式 https://github.com/mashirozx/Pixiv-Nginx 先进行配置)
2. 打开浏览器的「Dev Console / 开发者工具 / F12」，切换至「Network / 网络」标签
3. 开启「Preserve log / 持续记录」
4. 在「Filter / 筛选」文本框中输入「callback?」
5. 登录您的 Pixiv 账号
6. 成功登录后，会出现一个类似「https://app-api.pixiv.net/.../callback?state=...&code=...」的字段
7. 将「code」后面的参数输入本程序
Code: YNb2Ts2HAwrWU27EFeKtiHfOXsPyvMEso5-8STI4ulA
!Error at 2021-09-28 21:01:34:
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 706, in urlopen
  File "urllib3\connectionpool.py", line 382, in _make_request
  File "urllib3\connectionpool.py", line 1010, in _validate_conn
  File "urllib3\connection.py", line 421, in connect
  File "urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
  File "ssl.py", line 423, in wrap_socket
  File "ssl.py", line 870, in _create
  File "ssl.py", line 1139, in do_handshake
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 449, in send
  File "urllib3\connectionpool.py", line 756, in urlopen
  File "urllib3\util\retry.py", line 532, in increment
  File "urllib3\packages\six.py", line 769, in reraise
  File "urllib3\connectionpool.py", line 706, in urlopen
  File "urllib3\connectionpool.py", line 382, in _make_request
  File "urllib3\connectionpool.py", line 1010, in _validate_conn
  File "urllib3\connection.py", line 421, in connect
  File "urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
  File "ssl.py", line 423, in wrap_socket
  File "ssl.py", line 870, in _create
  File "ssl.py", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(0, 'Error'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pixivpy3\api.py", line 61, in requests_call
  File "requests\sessions.py", line 590, in post
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests_toolbelt\adapters\host_header_ssl.py", line 43, in send
  File "requests\adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(0, 'Error'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\YANGHU~1\AppData\Local\Temp\_MEI292282/app/lib/core/biu.py", line 154, in __login
    self.__loginAppAPI(**args)
  File "C:\Users\YANGHU~1\AppData\Local\Temp\_MEI292282/app/lib/core/biu.py", line 255, in __loginAppAPI
    self.api.login(username, password)
  File "pixivpy3\api.py", line 75, in login
  File "pixivpy3\api.py", line 114, in auth
  File "pixivpy3\api.py", line 66, in requests_call
pixivpy3.utils.PixivError: requests POST https://210.140.131.220/auth/token error: ('Connection aborted.', OSError(0, 'Error'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 382, in _make_request
  File "urllib3\connectionpool.py", line 1010, in _validate_conn
  File "urllib3\connection.py", line 421, in connect
  File "urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
  File "ssl.py", line 423, in wrap_socket
  File "ssl.py", line 870, in _create
  File "ssl.py", line 1139, in do_handshake
socket.timeout: _ssl.c:1074: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 449, in send
  File "urllib3\connectionpool.py", line 756, in urlopen
  File "urllib3\util\retry.py", line 532, in increment
  File "urllib3\packages\six.py", line 770, in reraise
  File "urllib3\connectionpool.py", line 706, in urlopen
  File "urllib3\connectionpool.py", line 385, in _make_request
  File "urllib3\connectionpool.py", line 337, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='210.140.131.220', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\YANGHU~1\AppData\Local\Temp\_MEI292282/app/lib/common/login_helper/main.py", line 77, in login
    return self.tokenG.login(host=self.authTokenURL, newCode=True, kw=kw)
  File "C:\Users\YANGHU~1\AppData\Local\Temp\_MEI292282\app\lib\common\login_helper\token.py", line 85, in login
    **kw,
  File "requests\sessions.py", line 590, in post
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests\adapters.py", line 529, in send
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='210.140.131.220', port=443): Read timed out. (read timeout=10)

[PixivBiu] 获取 Token 时出错，请重试。
```

**Comment by txperl** [comment]
从程序的提示信息来看，貌似程序的登录请求都没有走您软路由的代理。可以检查一下软路由代理的规则，或者直接在程序 `config.yml` 中指定地址。

**Comment by txperl** [comment]
或者你可以试试新编译的 Release 版本。

https://github.com/txperl/PixivBiu/releases/tag/test

**Comment by yanghuan** [comment]
配置了`config.yml`字段`proxy`, 还是有报错,我在浏览器上也无法直接访问https://210.140.131.223/auth/token（已经通过代理访问）
```
[PixivBiu] 检测网络状态...
[PixivBiu] 无法访问 Pixiv，启用 byPassSni API
[PixivBiu] 由于 Pixiv 禁止了账号密码登陆方式，暂时只能使用 Token 进行登录
是否开始手动获取 Token 后继续使用? (y / n): y
[Login Helper] 即将开始进行网络检测，此过程可以减少因网络问题导致的无法正常使用 PixivBiu 的概率
[Login Helper] 开始进行网络检测...
检测到内容为 127.0.0.1:1082 的代理监听地址，是否需要更改? (y / n): n
[Network Checker] https://public-api.secure.pixiv.net ❌
[Network Checker] https://1.0.0.1/dns-query ✔️
[Network Checker] https://1.1.1.1/dns-query ✔️
[Network Checker] https://[2606:4700:4700::1001]/dns-query ✔️
[Network Checker] https://[2606:4700:4700::1111]/dns-query ✔️
[Network Checker] https://cloudflare-dns.com/dns-query ✔️
[Login] 请按以下步骤进行操作:
注意: 程序每次启动时要求获取的 Code 都不同，不可复用之前获取到的，且 Code 不带有引号
1. 访问「https://app-api.pixiv.net/web/v1/login?code_challenge=cJF95YBm4JbpxWJt8Q2XFM1FGweR9UjZiqhJ_4hvewA&code_challenge_method=S256&client=pixiv-android」
   (若您别无他法，还是不能访问以上网址，那可参考此方式 https://github.com/mashirozx/Pixiv-Nginx 先进行配置)
2. 打开浏览器的「Dev Console / 开发者工具 / F12」，切换至「Network / 网络」标签
3. 开启「Preserve log / 持续记录」
4. 在「Filter / 筛选」文本框中输入「callback?」
5. 登录您的 Pixiv 账号
6. 成功登录后，会出现一个类似「https://app-api.pixiv.net/.../callback?state=...&code=...」的字段
7. 将「code」后面的参数输入本程序
Code: yjBl36MBmeNHxygF4_rEw5_M6htMzXLJnAFXmzppgHI
!Error at 2021-10-05 21:06:01:
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 706, in urlopen
  File "urllib3\connectionpool.py", line 382, in _make_request
  File "urllib3\connectionpool.py", line 1010, in _validate_conn
  File "urllib3\connection.py", line 421, in connect
  File "urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
  File "ssl.py", line 423, in wrap_socket
  File "ssl.py", line 870, in _create
  File "ssl.py", line 1139, in do_handshake
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 449, in send
  File "urllib3\connectionpool.py", line 756, in urlopen
  File "urllib3\util\retry.py", line 532, in increment
  File "urllib3\packages\six.py", line 769, in reraise
  File "urllib3\connectionpool.py", line 706, in urlopen
  File "urllib3\connectionpool.py", line 382, in _make_request
  File "urllib3\connectionpool.py", line 1010, in _validate_conn
  File "urllib3\connection.py", line 421, in connect
  File "urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
  File "ssl.py", line 423, in wrap_socket
  File "ssl.py", line 870, in _create
  File "ssl.py", line 1139, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(0, 'Error'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pixivpy3\api.py", line 61, in requests_call
  File "requests\sessions.py", line 590, in post
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests_toolbelt\adapters\host_header_ssl.py", line 43, in send
  File "requests\adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(0, 'Error'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\YANGHU~1\AppData\Local\Temp\_MEI118362/app/lib/core/biu.py", line 154, in __login
    self.__loginAppAPI(**args)
  File "C:\Users\YANGHU~1\AppData\Local\Temp\_MEI118362/app/lib/core/biu.py", line 255, in __loginAppAPI
    self.api.login(username, password)
  File "pixivpy3\api.py", line 75, in login
  File "pixivpy3\api.py", line 114, in auth
  File "pixivpy3\api.py", line 66, in requests_call
pixivpy3.utils.PixivError: requests POST https://210.140.131.223/auth/token error: ('Connection aborted.', OSError(0, 'Error'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 696, in urlopen
  File "urllib3\connectionpool.py", line 964, in _prepare_proxy
  File "urllib3\connection.py", line 421, in connect
  File "urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
  File "ssl.py", line 423, in wrap_socket
  File "ssl.py", line 870, in _create
  File "ssl.py", line 1139, in do_handshake
socket.timeout: _ssl.c:1074: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 449, in send
  File "urllib3\connectionpool.py", line 756, in urlopen
  File "urllib3\util\retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='210.140.131.200', port=443): Max retries exceeded with url: /auth/token (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1074: The handshake operation timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\YANGHU~1\AppData\Local\Temp\_MEI118362/app/lib/common/login_helper/main.py", line 77, in login
    return self.tokenG.login(host=self.authTokenURL, newCode=True, kw=kw)
  File "C:\Users\YANGHU~1\AppData\Local\Temp\_MEI118362\app\lib\common\login_helper\token.py", line 85, in login
    **kw,
  File "requests\sessions.py", line 590, in post
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests\adapters.py", line 510, in send
requests.exceptions.ProxyError: HTTPSConnectionPool(host='210.140.131.200', port=443): Max retries exceeded with url: /auth/token (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1074: The handshake operation timed out')))

```

**Comment by kendriz828** [comment]
我设置了proxy地址但是无法显示code，登录后没有登陆成功的提示，显示为空白页面
代码总是显示下面两处错误，请问该如何解决？

[PixivBiu] 检测网络状态...
[PixivBiu] 由于 Pixiv 禁止了账号密码登陆方式，暂时只能使用 Token 进行登录
是否开始手动获取 Token 后继续使用? (y / n): y
[Login Helper] 即将开始进行网络检测，此过程可以减少因网络问题导致的无法正常使用 PixivBiu 的概率
[Login Helper] 开始进行网络检测...
未能检测到系统代理地址，是否需要手动设置? (y / n): y
请输入代理监听地址(可留空): http://127.0.0.1:10809/
[Network Checker] https://public-api.secure.pixiv.net ✔️
[Network Checker] https://1.0.0.1/dns-query ✔️
[Network Checker] https://1.1.1.1/dns-query ✔️
[Network Checker] https://[2606:4700:4700::1001]/dns-query ❌
[Network Checker] https://[2606:4700:4700::1111]/dns-query ❌
[Network Checker] https://cloudflare-dns.com/dns-query ✔️
[Login] 请按以下步骤进行操作:
注意: 程序每次启动时要求获取的 Code 都不同，不可复用之前获取到的，且 Code 不带有引号
1. 访问「https://app-api.pixiv.net/web/v1/login?code_challenge=T1tAo7PdV2i4mpN7Fk81OuGsAO5IvJQ9FvjqaUzHUB8&code_challenge_method=S256&client=pixiv-android」
   (若您别无他法，还是不能访问以上网址，那可参考此方式 https://github.com/mashirozx/Pixiv-Nginx 先进行配置)
2. 打开浏览器的「Dev Console / 开发者工具 / F12」，切换至「Network / 网络」标签
3. 开启「Preserve log / 持续记录」
4. 在「Filter / 筛选」文本框中输入「callback?」
5. 登录您的 Pixiv 账号
6. 成功登录后，会出现一个类似「https://app-api.pixiv.net/.../callback?state=...&code=...」的字段
7. 将「code」后面的参数输入本程序
Code:

**Comment by txperl** [comment]
> 我设置了proxy地址但是无法显示code，登录后没有登陆成功的提示，显示为空白页面
> 代码总是显示下面两处错误，请问该如何解决？
> 
> [PixivBiu] 检测网络状态...
> [PixivBiu] 由于 Pixiv 禁止了账号密码登陆方式，暂时只能使用 Token 进行登录
> 是否开始手动获取 Token 后继续使用? (y / n): y
> [Login Helper] 即将开始进行网络检测，此过程可以减少因网络问题导致的无法正常使用 PixivBiu 的概率
> [Login Helper] 开始进行网络检测...
> 未能检测到系统代理地址，是否需要手动设置? (y / n): y
> 请输入代理监听地址(可留空): http://127.0.0.1:10809/
> [Network Checker] https://public-api.secure.pixiv.net ✔️
> [Network Checker] https://1.0.0.1/dns-query ✔️
> [Network Checker] https://1.1.1.1/dns-query ✔️
> [Network Checker] https://[2606:4700:4700::1001]/dns-query ❌
> [Network Checker] https://[2606:4700:4700::1111]/dns-query ❌
> [Network Checker] https://cloudflare-dns.com/dns-query ✔️
> [Login] 请按以下步骤进行操作:
> 注意: 程序每次启动时要求获取的 Code 都不同，不可复用之前获取到的，且 Code 不带有引号
> 1. 访问「https://app-api.pixiv.net/web/v1/login?code_challenge=T1tAo7PdV2i4mpN7Fk81OuGsAO5IvJQ9FvjqaUzHUB8&code_challenge_method=S256&client=pixiv-android」
>    (若您别无他法，还是不能访问以上网址，那可参考此方式 https://github.com/mashirozx/Pixiv-Nginx 先进行配置)
> 2. 打开浏览器的「Dev Console / 开发者工具 / F12」，切换至「Network / 网络」标签
> 3. 开启「Preserve log / 持续记录」
> 4. 在「Filter / 筛选」文本框中输入「callback?」
> 5. 登录您的 Pixiv 账号
> 6. 成功登录后，会出现一个类似「https://app-api.pixiv.net/.../callback?state=...&code=...」的字段
> 7. 将「code」后面的参数输入本程序
> Code: 

你这个没有错误，你需要按步骤打开浏览器的开发者工具查询 code。

**Comment by yanghuan** [comment]
好的，感谢解答，我也在尝试尝试
