### ISSUE TITLE
玄学登录

### ISSUE THREAD

**Issue by z0z0r4** [txperl/PixivBiu#29]
看起来并不是账户问题，该工具有debug模式吗？（我怀疑是代理...
![image](https://user-images.githubusercontent.com/78744121/156905641-f7acc83f-cada-4d4b-a9b7-7cb74ec89972.png)
上次无法登录是您建议换号，但我这次重开几次后却可以了

**Comment by z0z0r4** [comment]
另外...在Linux登录时为啥会这样
```
!Error at 2022-03-06 10:28:34:
Traceback (most recent call last):
  File "/pixiv/PixivBiu/app/lib/core/biu.py", line 136, in __login
    args = {"token": tokenFile["token"], }
TypeError: 'bool' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pixiv/PixivBiu/app/lib/core/biu.py", line 140, in __login
    self.__loginPublicAPI(**args)
  File "/pixiv/PixivBiu/app/lib/core/biu.py", line 177, in __loginPublicAPI
    self.api = PixivAPI(**_REQUESTS_KWARGS)
NameError: name 'PixivAPI' is not defined

```

python3，已经安装了pip里面的库
```
[root@VM-4-4-centos PixivBiu]# pip3 install -r requirements.txt 
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Looking in indexes: http://mirrors.tencentyun.com//pypi/simple/
Requirement already satisfied: flask in /usr/local/lib64/python3.6/site-packages (from -r requirements.txt (line 1)) (2.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 2)) (2.27.1)
Requirement already satisfied: pyyaml in /usr/lib64/python3.6/site-packages (from -r requirements.txt (line 3)) (3.12)
Requirement already satisfied: Pillow in /usr/local/lib64/python3.6/site-packages (from -r requirements.txt (line 4)) (8.4.0)
Requirement already satisfied: pixivpy in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 5)) (3.7.0)
Requirement already satisfied: PySocks in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 6)) (1.6.8)
Requirement already satisfied: click>=7.1.2 in /usr/local/lib/python3.6/site-packages (from flask->-r requirements.txt (line 1)) (8.0.4)
Requirement already satisfied: itsdangerous>=2.0 in /usr/local/lib/python3.6/site-packages (from flask->-r requirements.txt (line 1)) (2.0.1)
Requirement already satisfied: Werkzeug>=2.0 in /usr/local/lib/python3.6/site-packages (from flask->-r requirements.txt (line 1)) (2.0.3)
Requirement already satisfied: Jinja2>=3.0 in /usr/local/lib/python3.6/site-packages (from flask->-r requirements.txt (line 1)) (3.0.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests->-r requirements.txt (line 2)) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.6/site-packages (from requests->-r requirements.txt (line 2)) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.6/site-packages (from requests->-r requirements.txt (line 2)) (2.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3.6/site-packages (from requests->-r requirements.txt (line 2)) (1.24.2)
Requirement already satisfied: cloudscraper<1.2.50,>=1.0 in /usr/local/lib/python3.6/site-packages (from pixivpy->-r requirements.txt (line 5)) (1.2.48)
Requirement already satisfied: requests-toolbelt>=0.9.1 in /usr/local/lib/python3.6/site-packages (from pixivpy->-r requirements.txt (line 5)) (0.9.1)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.6/site-packages (from click>=7.1.2->flask->-r requirements.txt (line 1)) (1.2.0)
Requirement already satisfied: pyparsing>=2.4.7 in /usr/local/lib/python3.6/site-packages (from cloudscraper<1.2.50,>=1.0->pixivpy->-r requirements.txt (line 5)) (3.0.7)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib64/python3.6/site-packages (from Jinja2>=3.0->flask->-r requirements.txt (line 1)) (2.0.1)
Requirement already satisfied: dataclasses in /usr/local/lib/python3.6/site-packages (from Werkzeug>=2.0->flask->-r requirements.txt (line 1)) (0.8)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.6/site-packages (from importlib-metadata->click>=7.1.2->flask->-r requirements.txt (line 1)) (3.6.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[root@VM-4-4-centos PixivBiu]# python3 main.py 
[Altfe] ;)
[PixivBiu] 检测网络状态...
[PixivBiu] 由于 Pixiv 禁止了账号密码登陆方式，暂时只能使用 Token 进行登录
是否继续? (y / n): y
[Login Helper] 即将开始进行网络检测，此过程可以减少因网络问题导致的无法正常使用 PixivBiu 的概率
[Login Helper] 开始进行网络检测...
未能检测到代理地址，是否需要手动设置? (y / n): n
[Network Checker] https://public-api.secure.pixiv.net [succeeded]
[Network Checker] https://1.0.0.1/dns-query [succeeded]
[Network Checker] https://dns.alidns.com/dns-query [succeeded]
[Network Checker] https://doh.dns.sb/dns-query [succeeded]
[Network Checker] https://doh.opendns.com/dns-query [succeeded]
[Network Checker] https://[2606:4700:4700::1001]/dns-query [failed]
[Network Checker] https://[2606:4700:4700::1111]/dns-query [failed]
[Network Checker] https://cloudflare-dns.com/dns-query [succeeded]
[Network Checker] https://dns.google/dns-query [succeeded]
[Login] 请按以下步骤进行操作:
注意: 程序每次启动时要求获取的 Code 都不同，不可复用之前获取到的，且 Code 不带有引号
1. 访问 https://app-api.pixiv.net/web/v1/login?code_challenge=6oA_GF3gZ_Gs090SvllGtN8psEPfBGvN-1IqLPCEZfw&code_challenge_method=S256&client=pixiv-android
   (若您别无他法，还是无法访问以上网址，那可参考此方式 https://github.com/mashirozx/Pixiv-Nginx 先进行配置)
打开浏览器的「Dev Console / 开发者工具 / F12」，切换至「Network / 网络」标签
开启「Preserve log / 持续记录」
在「Filter / 筛选」文本框中输入「callback?」
登录您的 Pixiv 账号
成功登录后，会出现一个类似「https://app-api.pixiv.net/.../callback?state=...&code=...」的字段
将「code」后面的参数输入本程序
Code: ********
!Error at 2022-03-06 10:28:34:
Traceback (most recent call last):
  File "/pixiv/PixivBiu/app/lib/core/biu.py", line 136, in __login
    args = {"token": tokenFile["token"], }
TypeError: 'bool' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pixiv/PixivBiu/app/lib/core/biu.py", line 140, in __login
    self.__loginPublicAPI(**args)
  File "/pixiv/PixivBiu/app/lib/core/biu.py", line 177, in __loginPublicAPI
    self.api = PixivAPI(**_REQUESTS_KWARGS)
NameError: name 'PixivAPI' is not defined

按任意键退出...
```

**Comment by z0z0r4** [comment]
尝试更新python3.10后
```
[root@VM-4-4-centos PixivBiu]# python3.10 main.py 
[Altfe] ;)
[PixivBiu] 检测网络状态...
[PixivBiu] 由于 Pixiv 禁止了账号密码登陆方式，暂时只能使用 Token 进行登录
是否继续? (y / n): y
[Login Helper] 即将开始进行网络检测，此过程可以减少因网络问题导致的无法正常使用 PixivBiu 的概率
[Login Helper] 开始进行网络检测...
未能检测到代理地址，是否需要手动设置? (y / n): n
[Network Checker] https://public-api.secure.pixiv.net [succeeded]
[Network Checker] https://1.0.0.1/dns-query [succeeded]
[Network Checker] https://dns.alidns.com/dns-query [succeeded]
[Network Checker] https://doh.dns.sb/dns-query [succeeded]
[Network Checker] https://doh.opendns.com/dns-query [succeeded]
[Network Checker] https://[2606:4700:4700::1001]/dns-query [failed]
[Network Checker] https://[2606:4700:4700::1111]/dns-query [failed]
[Network Checker] https://cloudflare-dns.com/dns-query [succeeded]
[Network Checker] https://dns.google/dns-query [succeeded]
[Login] 请按以下步骤进行操作:
注意: 程序每次启动时要求获取的 Code 都不同，不可复用之前获取到的，且 Code 不带有引号
1. 访问 https://app-api.pixiv.net/web/v1/login?code_challenge=bthd_VBDvZoSzEUfT0FwavzVpi7zWbL0fzJmie_l_sw&code_challenge_method=S256&client=pixiv-android
   (若您别无他法，还是无法访问以上网址，那可参考此方式 https://github.com/mashirozx/Pixiv-Nginx 先进行配置)
打开浏览器的「Dev Console / 开发者工具 / F12」，切换至「Network / 网络」标签
开启「Preserve log / 持续记录」
在「Filter / 筛选」文本框中输入「callback?」
登录您的 Pixiv 账号
成功登录后，会出现一个类似「https://app-api.pixiv.net/.../callback?state=...&code=...」的字段
将「code」后面的参数输入本程序
Code: zTnQnDFE5vqhCgf4nIMdsAqrxXM6j9CuYQoX9BKFF1A
!Error at 2022-03-06 11:39:35:
Traceback (most recent call last):
  File "/pixiv/PixivBiu/app/lib/core/biu.py", line 140, in __login
    self.__loginPublicAPI(**args)
  File "/pixiv/PixivBiu/app/lib/core/biu.py", line 177, in __loginPublicAPI
    self.api = PixivAPI(**_REQUESTS_KWARGS)
NameError: name 'PixivAPI' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.10/ssl.py", line 1061, in _create
    self._sslobj = self._context._wrap_socket(
ssl.SSLError: Cannot create a client socket with a PROTOCOL_TLS_SERVER context (_ssl.c:801)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='public-api.secure.pixiv.net', port=443): Max retries exceeded with url: /auth/token (Caused by SSLError(SSLError(0, 'Cannot create a client socket with a PROTOCOL_TLS_SERVER context (_ssl.c:801)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pixiv/PixivBiu/app/lib/common/login_helper/main.py", line 81, in login
    return self.tokenG.login(host=self.authTokenURL, newCode=True, kw=kw)
  File "/pixiv/PixivBiu/app/lib/common/login_helper/token.py", line 68, in login
    response = self.requests.post(
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='public-api.secure.pixiv.net', port=443): Max retries exceeded with url: /auth/token (Caused by SSLError(SSLError(0, 'Cannot create a client socket with a PROTOCOL_TLS_SERVER context (_ssl.c:801)')))

[PixivBiu] 获取 Token 时出错，请重试。
按任意键退出...

[root@VM-4-4-centos PixivBiu]# python3.10 --version
Python 3.10.0

[root@VM-4-4-centos PixivBiu]# pip3.10 install -r requirements.txt 
Looking in indexes: https://pypi.python.org/simple
Requirement already satisfied: flask in /usr/local/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (2.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (2.27.1)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (6.0)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (9.0.1)
Requirement already satisfied: pixivpy in /usr/local/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (3.7.0)
Requirement already satisfied: PySocks in /usr/local/lib/python3.10/site-packages (from -r requirements.txt (line 6)) (1.7.1)
Requirement already satisfied: click>=7.1.2 in /usr/local/lib/python3.10/site-packages (from flask->-r requirements.txt (line 1)) (8.0.4)
Requirement already satisfied: Jinja2>=3.0 in /usr/local/lib/python3.10/site-packages (from flask->-r requirements.txt (line 1)) (3.0.3)
Requirement already satisfied: Werkzeug>=2.0 in /usr/local/lib/python3.10/site-packages (from flask->-r requirements.txt (line 1)) (2.0.3)
Requirement already satisfied: itsdangerous>=2.0 in /usr/local/lib/python3.10/site-packages (from flask->-r requirements.txt (line 1)) (2.1.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/site-packages (from requests->-r requirements.txt (line 2)) (1.26.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/site-packages (from requests->-r requirements.txt (line 2)) (2.0.12)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/site-packages (from requests->-r requirements.txt (line 2)) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/site-packages (from requests->-r requirements.txt (line 2)) (3.3)
Requirement already satisfied: cloudscraper<1.2.50,>=1.0 in /usr/local/lib/python3.10/site-packages (from pixivpy->-r requirements.txt (line 5)) (1.2.48)
Requirement already satisfied: requests-toolbelt>=0.9.1 in /usr/local/lib/python3.10/site-packages (from pixivpy->-r requirements.txt (line 5)) (0.9.1)
Requirement already satisfied: pyparsing>=2.4.7 in /usr/local/lib/python3.10/site-packages (from cloudscraper<1.2.50,>=1.0->pixivpy->-r requirements.txt (line 5)) (3.0.7)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/site-packages (from Jinja2>=3.0->flask->-r requirements.txt (line 1)) (2.1.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: You are using pip version 21.2.3; however, version 22.0.3 is available.
You should consider upgrading via the '/usr/local/bin/python3.10 -m pip install --upgrade pip' command.
[root@VM-4-4-centos PixivBiu]# 
```

**Comment by txperl** [comment]
不好意思，最新版的 PixivPy 模块把 Public API 移除了，导致无法正常使用。可以指定 `pixivpy==3.6.2` 解决。

我会尽快修复这个问题，感谢反馈。

**Comment by txperl** [comment]
已于 [ca177fb](https://github.com/txperl/PixivBiu/commit/ca177fb211036a70fcd291019735e64bf3072302) 版本修复。
