### ISSUE TITLE
AttributeError: 'ByPassSniApi' object has no attribute 'hosts'

### ISSUE THREAD

**Issue by eeezae** [txperl/PixivBiu#33]
* Version: Newest version(2.5.2)
* Python: 3.9
* Platform: macOS M1
* Bug:
```
!Error at 2022-06-27 09:10:43:
Traceback (most recent call last):
  File "/Users/mc/Project/Python/PixivBiu/altfe/handle.py", line 32, in do
    r = cls.osGet("PLUGIN", rCMD)().run(cmd.split(rCMD)[1])
  File "/Users/mc/Project/Python/PixivBiu/app/plugin/get/idmarks.py", line 29, in run
    "rst": self.gank(args["ops"], args["fun"].copy()),
  File "/Users/mc/Project/Python/PixivBiu/app/plugin/get/idmarks.py", line 48, in gank
    t = self.CORE.biu.api.user_bookmarks_illust(**argg)
  File "/Users/mc/Library/Caches/pypoetry/virtualenvs/pixivbiu-OlCVziVP-py3.9/lib/python3.9/site-packages/pixivpy3/aapi.py", line 132, in user_bookmarks_illust
    url = '%s/v1/user/bookmarks/illust' % self.hosts
AttributeError: 'ByPassSniApi' object has no attribute 'hosts'
```

**Comment by txperl** [comment]
请问在获取 Token 网络检测有 succeeded 的吗？
