### ISSUE TITLE
关于由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败

### ISSUE THREAD

**Issue by zoukai333** [txperl/PixivBiu#36]
一搜索就会这样，但是可以正常打开排行榜并且下载图片
!Error at 2022-08-27 20:01:34:
Traceback (most recent call last):
  File "urllib3\connection.py", line 175, in _new_conn
  File "urllib3\util\connection.py", line 96, in create_connection
  File "urllib3\util\connection.py", line 86, in create_connection
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 706, in urlopen
  File "urllib3\connectionpool.py", line 382, in _make_request
  File "urllib3\connectionpool.py", line 1010, in _validate_conn
  File "urllib3\connection.py", line 358, in connect
  File "urllib3\connection.py", line 187, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000017BF796C408>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 450, in send
  File "urllib3\connectionpool.py", line 756, in urlopen
  File "urllib3\util\retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='210.140.92.186', port=443): Max retries exceeded with url: /v1/search/illust?word=%E3%83%9C%E3%83%86%E8%85%B9&search_target=exact_match_for_tags&sort=date_desc&filter=for_ios&offset=120 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017BF796C408>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pixivpy3\api.py", line 60, in requests_call
  File "requests\sessions.py", line 542, in get
  File "requests\sessions.py", line 529, in request
  File "requests\sessions.py", line 645, in send
  File "requests_toolbelt\adapters\host_header_ssl.py", line 43, in send
  File "requests\adapters.py", line 519, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='210.140.92.186', port=443): Max retries exceeded with url: /v1/search/illust?word=%E3%83%9C%E3%83%86%E8%85%B9&search_target=exact_match_for_tags&sort=date_desc&filter=for_ios&offset=120 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017BF796C408>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "altfe\handle.py", line 32, in do
  File "C:\Users\zoukai\AppData\Local\Temp\_MEI117042/app/plugin/search/works.py", line 45, in run
    rst = self.appWorks(args["ops"].copy(), args["fun"].copy())
  File "C:\Users\zoukai\AppData\Local\Temp\_MEI117042/app/plugin/search/works.py", line 81, in appWorks
    r["data"] += x.result()
  File "concurrent\futures\_base.py", line 428, in result
  File "concurrent\futures\_base.py", line 384, in __get_result
  File "concurrent\futures\thread.py", line 57, in run
  File "C:\Users\zoukai\AppData\Local\Temp\_MEI117042/app/plugin/search/works.py", line 99, in __thread_appWorks
    data = self.CORE.biu.api.search_illust(**kw)
  File "pixivpy3\aapi.py", line 294, in search_illust
  File "pixivpy3\aapi.py", line 47, in no_auth_requests_call
  File "pixivpy3\api.py", line 75, in requests_call
pixivpy3.utils.PixivError: requests GET https://210.140.92.186/v1/search/illust error: HTTPSConnectionPool(host='210.140.92.186', port=443): Max retries exceeded with url: /v1/search/illust?word=%E3%83%9C%E3%83%86%E8%85%B9&search_target=exact_match_for_tags&sort=date_desc&filter=for_ios&offset=120 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017BF796C408>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

**Comment by txperl** [comment]
`bypassSNI` 模式连接可能会不太稳定，然后就会出现上述的各种报错，都是网络问题引起的。

程序暂时还无法做进一步优化，只能调整一下自己的网络情况，比如使用代理或者尝试其他网络。
